apiVersion: harness.io/v1
kind: Component
type: service
identifier: todd_test_three
name: Todd Test Three
owner: user:natalie.finnegan
orgIdentifier: default
projectIdentifier: default_project
spec:
  lifecycle: development
  sourceCode:
    provider: Github
    repoName: rbg-todd-test-three
    connectorRef: account.githubharnesssandbox
    branch: main
    monoRepo: false
    url: https://github.com/harness-idp-sandbox/rbg-todd-test-three/tree/main
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rbg-todd-test-three
    backstage.io/kubernetes-label-selector: app=toddtestthree
    harness.io/pipelines: |
      Build and Deploy: https://app.harness.io/ng/account/sPn9anBcT3-jpii6rWBlTg/all/orgs/default/projects/default_project/pipelines/Java_App_Provisioner/pipeline-studio/?storeType=INLINE
  links:
  - title: Website
    url: http://harness.io
  tags:
  - java
